# Generated by Django 3.1.4 on 2020-12-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ornekform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ornekformdatabase',
            name='budged',
            field=models.IntegerField(max_length=50, verbose_name='budget'),
        ),
    ]
