# Generated by Django 3.1.4 on 2020-12-06 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ornekform', '0002_auto_20201206_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ornekformdatabase',
            name='budged',
            field=models.CharField(max_length=50, verbose_name='budget'),
        ),
    ]
